#!/bin/sh
expectedDirectory=$1
tagPattern=$2

correctDirectory=$(in-correct-directory $expectedDirectory)
if [ "$correctDirectory" = "1" ]; then
  echo "Error: You need to be in the $expectedDirectory folder"
  exit 1
fi

notPushed=$(has-unpushed-commits)
if [ "$notPushed" = "1" ]; then
  echo "Error: The branch is not up to date with the remove. Make sure to push your changes or pull from the remote."
  exit 1
fi


tag=$(latest-tag $tagPattern)
read -p "Push tag $tag (y/n)? " shouldPushTag
if [ "$shouldPushTag" = "y" ]; then
  git tag $tag
  git push origin $tag
else
  echo "Bye."
fi
